require( 'sinatra' )
require( 'sinatra/contrib/all' )
require( 'pry' )
require_relative( '../models/loan.rb' )
require_relative( '../models/member.rb' )
require_relative( '../models/book.rb' )
require_relative( '../models/genre.rb' )
also_reload( '../models/*' )
